export const translation = {
    localization: {
        cz: {
            headName: "poznámky",
            listTitle: "Popisek",
            listEdit: "upravit",
            listDelete: "odstranit",
            listInfo: "detail",
            btnAddNote: "přidat poznámku",
            modalNewName: "Nová poznáka",
            modalEditName: "Editování poznámky",
            modalLabel: "Popisek",
            modalPlaceholder: "popisek",
            modalSave: "Uložit",
            modalValidMsg: "Vyplňte popisek",
            confirmModalName: "Opravdu odstranit poznámku?",
            confirmModalYes: "Ano",
            confirmModalNo: "Ne",
            noteInfoName: "Detail poznámky",
            noteInfoTitle: "Popisek",
            noteInfoBack: "Zpět",
            pageNotFound: "Stránka nenalezena",
        },
        en: {
            headName: "notes",
            listTitle: "Title",
            listEdit: "edit",
            listDelete: "remove",
            listInfo: "info",
            btnAddNote: "add note",
            modalNewName: "New note",
            modalEditName: "Editing note",
            modalLabel: "Description",
            modalPlaceholder: "description",
            modalSave: "Save",
            modalValidMsg: "Fill in description",
            confirmModalName: "Delete note?",
            confirmModalYes: "Yes",
            confirmModalNo: "No",
            noteInfoName: "Detail of note",
            noteInfoTitle: "Title",
            noteInfoBack: "Back",
            pageNotFound: "Page not found",
        }
    }
}